<template>
  <div class="ele-body pet-board">
    <div v-if="['overview','settings'].includes(module)" class="mb"><el-button icon="el-icon-refresh" :loading="loading" @click="reload">刷新</el-button></div>
    <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb"/>
    <template v-if="module === 'overview'">
      <div class="stats"><el-card v-for="(label,key) in countLabels" :key="key" shadow="never"><div class="muted">{{ label }}</div><strong>{{ counts[key] || 0 }}</strong></el-card></div>
      <el-card shadow="never" class="mb"><h3>近30日新增用户</h3><el-table :data="growth" empty-text="暂无注册数据"><el-table-column prop="day" label="日期"/><el-table-column prop="total" label="新增用户"/></el-table></el-card>
      <el-card shadow="never"><h3>提醒类型统计</h3><el-table :data="types"><el-table-column label="类型"><template slot-scope="s">{{ format('type',s.row.type) }}</template></el-table-column><el-table-column prop="total" label="设置数"/><el-table-column prop="triggered" label="触发次数"/><el-table-column prop="completed" label="已完成"/><el-table-column label="完成率"><template slot-scope="s">{{ s.row.total ? (s.row.completed / s.row.total * 100).toFixed(1) : 0 }}%</template></el-table-column></el-table></el-card>
    </template>
    <el-card v-else-if="module === 'settings'" shadow="never" v-loading="loading">
      <el-form label-position="top"><el-form-item v-for="(label,key) in settingLabels" :key="key" :label="label"><el-input v-model="settings[key]" type="textarea" :rows="key.includes('privacy') || key.includes('agreement') ? 8 : 3" :maxlength="20000" show-word-limit/></el-form-item><el-alert title="订阅模板应与微信公众平台一致。字段映射使用模板字段名，对应 title（事项）或 due_at（到期时间）。未配置模板时仅发送站内提醒。" type="info" :closable="false" class="mb"/><el-button v-if="canEdit" type="primary" :loading="saving" @click="saveSettings">保存配置</el-button></el-form>
    </el-card>
    <el-card v-else shadow="never">
      <el-radio-group v-if="module==='places'" v-model="placeScope" class="mb" @change="changePlaceScope"><el-radio-button label="all">全部点位</el-radio-button><el-radio-button label="pending">待审核投稿</el-radio-button><el-radio-button label="user">全部用户投稿</el-radio-button></el-radio-group>
      <el-form inline @submit.native.prevent="search"><el-form-item><el-input v-model="query.keyword" clearable :placeholder="module==='records'?'宠物昵称 / 用户昵称 / 记录类型':'名称 / 昵称 / 用品'" @keyup.enter.native="search"/></el-form-item><el-form-item v-if="module !== 'members'"><el-input v-model="query.member_id" clearable placeholder="用户编号"/></el-form-item><el-form-item v-if="['records','reminders'].includes(module)"><el-input v-model="query.pet_id" clearable placeholder="宠物编号"/></el-form-item><el-form-item v-if="Object.keys(typeOptions).length"><el-select v-model="query.type" clearable placeholder="类型"><el-option v-for="(label,value) in typeOptions" :key="value" :label="label" :value="value"/></el-select></el-form-item><el-form-item v-if="module==='places'"><el-select v-model="query.category" clearable placeholder="分类"><el-option v-for="(label,value) in categories" :key="value" :label="label" :value="value"/></el-select></el-form-item><el-form-item v-if="statusOptions.length"><el-select v-model="query.status" clearable placeholder="状态"><el-option v-for="o in statusOptions" :key="o.value" :label="o.label" :value="o.value"/></el-select></el-form-item><el-form-item v-if="module==='places'"><el-select v-model="query.source" clearable placeholder="来源"><el-option label="官方点位" value="official"/><el-option label="用户投稿" value="user"/></el-select></el-form-item><el-form-item><el-date-picker v-model="range" type="datetimerange" value-format="yyyy-MM-dd HH:mm:ss" start-placeholder="开始时间" end-placeholder="结束时间"/></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form>
      <div class="mb"><el-button icon="el-icon-refresh" :loading="loading" @click="reload">刷新</el-button><el-button v-if="module==='places' && canEdit" type="primary" icon="el-icon-plus" @click="editPlace()">发布官方点位</el-button><el-button v-if="allowed('export')" :loading="exporting" @click="exportRows">导出查询结果</el-button><span class="muted" style="margin-left:16px">共 {{ total }} 条</span></div>
      <el-table v-loading="loading" :data="rows" border empty-text="暂无符合条件的数据"><el-table-column v-for="column in columns" :key="column[0]" :label="column[1]" :min-width="column[0]==='id'?75:140" show-overflow-tooltip><template slot-scope="s">{{ format(column[0],s.row[column[0]]) }}</template></el-table-column><el-table-column label="操作" min-width="220" fixed="right"><template slot-scope="s"><el-button v-if="allowed('detail')" type="text" @click="detail(s.row)">详情</el-button><template><el-button v-if="module==='members' && canEdit" type="text" @click="operate(s.row,'status')">{{ s.row.status===1?'停用':'启用' }}</el-button><el-button v-if="['pets','records'].includes(module) && canEdit" type="text" class="danger-text" @click="operate(s.row,'remove')">{{module==='records'?'删除':'异常清理'}}</el-button><template v-if="module==='places'"><el-button v-if="s.row.source==='official' && canEdit" type="text" @click="editPlace(s.row)">编辑</el-button><template v-if="s.row.status===0"><el-button v-if="allowed('approve')" type="text" @click="operate(s.row,'approve')">审核通过</el-button><el-button v-if="allowed('reject')" type="text" @click="operate(s.row,'reject')">驳回投稿</el-button></template><el-button v-if="[1,3].includes(s.row.status) && allowed('status')" type="text" @click="operate(s.row,'status')">{{ s.row.status===1?'下架':'上架' }}</el-button><el-button v-if="s.row.source==='official' && allowed('top')" type="text" @click="operate(s.row,'top')">{{ s.row.is_top?'取消置顶':'置顶' }}</el-button></template></template></template></el-table-column></el-table>
      <el-pagination class="pagination" :current-page.sync="page" :page-size="20" :total="total" layout="total, prev, pager, next" @current-change="reload"/>
    </el-card>
    <el-dialog title="详细资料" :visible.sync="detailOpen" width="88%" top="5vh" custom-class="pet-detail-dialog" append-to-body destroy-on-close>
      <div v-loading="detailLoading" class="detail-scroll">
        <el-descriptions v-if="detailData.item" title="基本信息" :column="2" border>
          <el-descriptions-item v-for="key in detailFields" :key="key" :label="labels[key]">
            <el-image v-if="key==='avatar' && detailData.item[key]" class="detail-avatar" :src="detailData.item[key]" :preview-src-list="[detailData.item[key]]" fit="cover"/>
            <span v-else>{{ format(key,detailData.item[key]) }}</span>
          </el-descriptions-item>
        </el-descriptions>
        <el-descriptions v-if="detailData.item && detailData.item.field_values && detailData.item.field_values.length" title="记录内容" :column="2" border class="relation-section"><el-descriptions-item v-for="f in detailData.item.field_values" :key="f.key" :label="f.label">{{f.value || '-'}}</el-descriptions-item></el-descriptions>
        <el-descriptions v-if="module==='records' && detailData.pet" title="宠物基本信息" :column="2" border class="relation-section"><el-descriptions-item v-for="key in ['id','name','type','breed','gender','birthday','weight','color','neutered','vaccination','character_note']" :key="key" :label="labels[key]">{{format(key,detailData.pet[key])}}</el-descriptions-item></el-descriptions>
        <el-empty v-else-if="module==='records' && detailData.item" description="关联宠物已不存在"/>
        <div v-if="module==='records' && detailData.pet" class="photos"><el-image v-for="url in detailData.pet.images" :key="url" :src="url" :preview-src-list="detailData.pet.images" fit="cover"/></div>
        <div v-if="detailData.item" class="photos"><el-image v-for="url in detailData.item.images || []" :key="url" :src="url" :preview-src-list="detailData.item.images" fit="cover"/></div>
        <section v-for="(label,key) in relationLabels" :key="key" class="relation-section">
          <template v-if="detailData[key]"><h3>{{ label }} · {{ detailData[key].total }}</h3>
            <el-table :data="detailData[key].list" border style="width:100%">
              <el-table-column v-for="col in relationColumns[key]" :key="col" :label="labels[col] || col" :min-width="['note','vaccination','character_note','field_values'].includes(col)?240:130">
                <template slot-scope="s"><div v-if="col==='images'" class="relation-photos"><el-image v-for="url in s.row.images" :key="url" :src="url" :preview-src-list="s.row.images" fit="cover"/><span v-if="!s.row.images.length">-</span></div><span v-else>{{format(col,s.row[col])}}</span></template>
              </el-table-column>
            </el-table>
          </template>
        </section>
        <el-pagination v-if="relationTotal > 20" class="pagination" :current-page.sync="detailPage" :total="relationTotal" :page-size="20" layout="prev,pager,next" @current-change="loadDetail"/>
      </div>
      <span slot="footer"><el-button @click="detailOpen=false">关闭</el-button></span>
    </el-dialog>
    <el-dialog :title="form.id?'编辑官方点位':'发布官方点位'" :visible.sync="formOpen" width="720px" :show-close="!uploading" :close-on-click-modal="!uploading" :close-on-press-escape="!uploading" append-to-body destroy-on-close><el-form ref="placeForm" :model="form" label-width="110px"><el-form-item v-for="f in placeFields" :key="f.key" :label="f.label" :prop="f.key" :rules="f.required ? [{required:true,message:'请填写'+f.label,trigger:'blur'}] : []"><el-select v-if="f.key==='category'" v-model="form.category" placeholder="请选择点位类型"><el-option v-for="(label,key) in formCategories" :key="key" :value="key" :label="label"/></el-select><div v-else-if="f.key==='address'"><el-input v-model="form.address" :maxlength="255" placeholder="请先从地图选择位置"><el-button slot="append" icon="el-icon-location" @click="mapOpen=true">地图选点</el-button></el-input><div v-if="form.latitude!==undefined && form.longitude!==undefined" class="muted">经度：{{form.longitude}} 纬度：{{form.latitude}}</div></div><el-input v-else v-model="form[f.key]" :maxlength="f.max" :type="f.max>500?'textarea':'text'" :rows="4" show-word-limit/></el-form-item><el-form-item label="场所图片"><upload-image v-model="form.images" :limit="9" @uploading="uploading=$event"/></el-form-item><el-alert title="坐标使用微信地图 GCJ-02 坐标。官方点位保存后直接公开展示。" type="info" :closable="false"/></el-form><span slot="footer"><el-button :disabled="uploading" @click="formOpen=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="uploading" @click="savePlace">保存发布</el-button></span></el-dialog>
    <amap-picker :visible.sync="mapOpen" :location="form" @select="chooseLocation"/>
  </div>
</template>
<script>
import {getPetList, getPetDetail, operatePet, savePetSettings} from '@/api/petknow'
import AmapPicker from './AmapPicker'
import UploadImage from '@/components/uploadImage'
const titles = {overview:'运营概览',members:'注册用户',pets:'宠物档案',records:'养护记录',places:'友好点位与投稿审核',reminders:'提醒与推送',settings:'小程序配置'}
const labels = {pet_name:'宠物昵称',pet_type:'宠物类型',pet_breed:'宠物品种',pet_gender:'宠物性别',pet_birthday:'宠物生日',pet_weight:'宠物体重 kg',type_name:'记录类型',field_values:'记录内容',id:'编号',member_id:'用户编号',member_name:'所属用户',pet_id:'宠物编号',name:'名称',nickname:'昵称',avatar:'头像',type:'类型',breed:'品种',gender:'性别',birthday:'生日',weight:'体重 kg',color:'毛色',neutered:'绝育情况',vaccination:'疫苗情况',character_note:'性格特点',note:'备注',images:'图片',create_time:'创建时间',update_time:'更新时间',login_time:'最近登录',occurred_at:'记录时间',product:'食物 / 用品 / 药品',amount:'用量 / 规格',method:'方式',next_at:'下次时间',category:'分类',address:'地址',latitude:'纬度',longitude:'经度',phone:'电话',hours:'开放时间',rules:'友好规则',source:'来源',status:'状态',rejection:'驳回原因',is_top:'置顶',review_user:'审核人编号',reviewed_at:'审核时间',title:'提醒事项',cycle:'周期',interval_days:'自定义天数',advance_days:'提前天数',due_at:'到期时间',enabled:'开启状态',subscribed:'本次订阅',sent_at:'触发时间',push_status:'推送结果',push_error:'推送说明',completed_at:'完成时间',reminder_count:'待办提醒数量',pet_count:'宠物数量',place_count:'投稿数量',rating:'评分',content:'评价内容'}
const columnKeys = {members:['id','nickname','pet_count','place_count','status','create_time'],pets:['id','name','member_name','type','breed','weight','create_time'],records:['id','member_name','pet_id','pet_name','pet_type','pet_breed','pet_gender','pet_birthday','pet_weight','type_name','occurred_at'],places:['id','name','category','source','member_name','status','create_time'],reminders:['id','title','member_name','pet_id','type','due_at','status','push_status','push_error']}
export default {
  name:'PetknowBoard', components:{UploadImage,AmapPicker}, props:{module:{type:String,required:true}},
  data() { return {loading:false,saving:false,uploading:false,exporting:false,error:'',rows:[],total:0,page:1,placeScope:'all',query:{},range:[],counts:{},growth:[],types:[],settings:{},recordTypes:{},detailOpen:false,detailLoading:false,detailData:{},detailId:0,detailPage:1,formOpen:false,mapOpen:false,form:{},labels,
    countLabels:{members:'注册用户',pets:'宠物档案',records:'养护记录',places:'友好点位',pending:'待审核投稿',reminders:'养护提醒',completed:'已完成提醒',failed:'微信推送失败'},
    settingLabels:{pet_announcement:'首页寄语',pet_about:'关于豆知',pet_reminder_template:'微信订阅消息模板 ID',pet_reminder_fields:'订阅模板字段映射 JSON',pet_default_days:'默认养护提醒天数 JSON',pet_privacy:'隐私政策正文',pet_agreement:'用户协议正文'},
    categories:{},activeCategories:{},
    relationLabels:{pets:'关联宠物',records:'养护时间轴',reminders:'关联提醒',places:'投稿记录',reviews:'用户评价'},
    relationColumns:{pets:['id','name','images','type','breed','gender','birthday','weight','color','neutered','vaccination','character_note','note','create_time','update_time'],records:['id','type_name','field_values','product','occurred_at','note'],reminders:['id','title','due_at','completed_at','push_status'],places:['id','name','category','rejection'],reviews:['id','member_id','rating','content','create_time']},
    placeFields:[{key:'name',label:'名称',max:100,required:true},{key:'category',label:'分类',required:true},{key:'address',label:'详细地址',max:255,required:true},{key:'phone',label:'电话',max:30},{key:'hours',label:'营业时间',max:100},{key:'rules',label:'友好规则',max:3000,required:true},{key:'note',label:'内部备注',max:3000}]
  } },
  computed:{formCategories(){return this.form.category && !this.activeCategories[this.form.category]?{...this.activeCategories,[this.form.category]:(this.categories[this.form.category] || this.form.category)+'（已停用）'}:this.activeCategories},typeOptions(){if(this.module==='pets'){return {cat:'猫咪',dog:'狗狗',other:'其他'}}if(['records','reminders'].includes(this.module)){return this.recordTypes}return {}},detailFields(){return Object.keys(this.detailData.item || {}).filter(key=>key!=='images' && key!=='openid' && key!=='field_values' && !(this.module==='records'&&['product','amount','method','type'].includes(key)) && this.labels[key])},title(){return titles[this.module]},columns(){return (columnKeys[this.module] || []).map(k=>[k,labels[k]])},canEdit(){return this.$hasPermission('pet:'+this.module+':edit')},statusOptions(){return (this.module==='places'?['待审核','已通过','已驳回','已下架']:this.module==='members'?['启用','停用']:this.module==='reminders'?['未完成','已完成']:[]).map((label,i)=>({label,value:this.module==='members'?i+1:i}))},relationTotal(){return Math.max(0,...Object.keys(this.relationLabels).map(k=>this.detailData[k]?this.detailData[k].total:0))}},
  mounted(){this.reload()},
  activated(){if(!this.loading){this.reload()}},
  methods:{
    allowed(action){return this.$hasPermission('pet:'+this.module+':'+action)},
    params(){return Object.assign({},this.query,{module:this.module,page:this.page,start:this.range && this.range[0],end:this.range && this.range[1]})},
    async reload(){if(this.loading){return}this.loading=true;this.error='';try{const r=await getPetList(this.params());this.recordTypes=r.record_types || this.recordTypes;this.categories=r.categories || this.categories;this.activeCategories=r.active_categories || this.activeCategories;if(this.module==='overview'){this.counts=r.counts;this.growth=r.growth;this.types=r.types}else if(this.module==='settings'){this.settings=r}else{this.rows=r.list;this.total=r.total;if(!r.list.length && this.page>1){this.page--;this.loading=false;return this.reload()}}}catch(e){this.error=e.message}finally{this.loading=false}},
    changePlaceScope(){this.query=this.placeScope==='pending'?{source:'user',status:0}:this.placeScope==='user'?{source:'user'}:{};this.range=[];this.page=1;this.reload()},
    search(){if(this.module==='places'){this.placeScope=this.query.source==='user'?(this.query.status===0?'pending':'user'):'all'}this.page=1;this.reload()},reset(){this.placeScope='all';this.query={};this.range=[];this.search()},
    format(key,value){if(key.startsWith('pet_')&&key!=='pet_id'){key=key.slice(4)}if(key==='field_values'){return (value || []).map(f=>f.label+'：'+(f.value || '-')).join('；')}if(value===null || value===undefined || value===''){return '-'}if(['create_time','update_time','login_time','occurred_at','next_at','due_at','reviewed_at','sent_at','completed_at'].includes(key)){return value?new Date(value*1000).toLocaleString('zh-CN',{hour12:false}):'-'}if(key==='status'){const m={members:{1:'启用',2:'停用'},places:{0:'待审核',1:'已通过',2:'已驳回',3:'已下架'},reminders:{0:'未完成',1:'已完成'}};return (m[this.module] || {})[value] || value}if(['enabled','subscribed','is_top'].includes(key)){return Number(value)?'是':'否'}const map={cat:'猫咪',dog:'狗狗',other:'其他',feed:'喂食',bath:'洗澡',internal:'内驱',external:'外驱',vaccine:'疫苗',exam:'体检',custom:'自定义',official:'官方',user:'用户投稿',male:'男生',female:'女生',unknown:'未填写',yes:'已绝育',no:'未绝育',once:'单次',daily:'每天',weekly:'每周',monthly:'每月',waiting:'待触发',sending:'发送中',sent:'微信已发送',failed:'微信发送失败',in_app:'站内提醒',...this.categories};return ['type','category','source','gender','neutered','cycle','push_status'].includes(key)?(key==='type' && this.recordTypes[value]) || map[value] || value:value},
    detail(row){this.detailId=row.id;this.detailPage=1;this.detailData={};this.detailOpen=true;this.loadDetail()},async loadDetail(){this.detailLoading=true;try{this.detailData=await getPetDetail({module:this.module,id:this.detailId,page:this.detailPage})}catch(e){this.$message.error(e.message)}finally{this.detailLoading=false}},
    async operate(row,action){try{let reason='';if(['reject','remove'].includes(action)){const r=await this.$prompt(action==='reject'?'请填写驳回原因':(this.module==='records'?'请填写删除原因（删除后无法恢复）':'请填写异常数据清理原因（删除后无法恢复）'),'确认操作',{inputValidator:v=>!!v && v.trim().length<=500,inputErrorMessage:'请填写1至500字原因'});reason=r.value}else {await this.$confirm('确认执行此操作？','确认',{type:'warning'})}await operatePet({module:this.module,id:row.id,action,reason});this.$message.success('操作成功');this.reload()}catch(e){if(e && e.message){this.$message.error(e.message)}}},
    chooseLocation(point){this.$set(this.form,'address',point.address);this.$set(this.form,'latitude',point.latitude);this.$set(this.form,'longitude',point.longitude);if(!this.form.name && point.name){this.$set(this.form,'name',point.name)}this.$refs.placeForm.clearValidate('address')},
    editPlace(row){if(!row && !Object.keys(this.activeCategories).length){return this.$message.warning('请先新增并启用点位类型')}this.form=row?JSON.parse(JSON.stringify(row)):{name:'',category:Object.keys(this.activeCategories)[0],address:'',latitude:undefined,longitude:undefined,phone:'',hours:'',rules:'',note:'',images:[]};if(row){this.form.latitude=Number(row.latitude);this.form.longitude=Number(row.longitude)}this.formOpen=true},
    savePlace(){this.$refs.placeForm.validate(async valid=>{if(!valid || this.saving || this.uploading){return}if(this.form.latitude===undefined || this.form.longitude===undefined){return this.$message.warning('请通过地图选择详细地址')}this.saving=true;try{await operatePet({...this.form,module:'places',action:'save'});this.formOpen=false;this.$message.success('点位已发布');this.reload()}catch(e){this.$message.error(e.message)}finally{this.saving=false}})},
    async saveSettings(){this.saving=true;try{await savePetSettings({...this.settings,module:'settings'});this.$message.success('配置已保存')}catch(e){this.$message.error(e.message)}finally{this.saving=false}},
    async exportRows(){if(this.exporting){return}this.exporting=true;try{let list=[];let page=1;let result;do{result=await getPetList({...this.params(),page,limit:100,export:'1'});list=list.concat(result.list);page++}while(list.length<result.total);const cell=v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const csv=[this.columns.map(c=>cell(c[1])).join(','),...list.map(row=>this.columns.map(c=>cell(this.format(c[0],row[c[0]]))).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=this.title+'.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){this.$message.error(e.message)}finally{this.exporting=false}}
  }
}
</script>
<style scoped>
.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:15px;margin-bottom:15px}.stats .el-card{margin:0}.stats strong{display:block;font-size:30px;margin-top:12px}.muted{color:#909399}.mb{margin-bottom:15px}.pagination{margin-top:20px;text-align:right}.detail-scroll{max-height:65vh;overflow:auto}.detail-scroll /deep/ .el-descriptions__table{table-layout:fixed}.detail-scroll /deep/ .el-descriptions-item__label{width:140px}.detail-avatar{width:64px;height:64px}.relation-section{margin-top:24px}.relation-section h3{font-size:16px;font-weight:600;margin:0 0 16px}.relation-photos{display:flex;flex-wrap:wrap;gap:6px}.relation-photos .el-image{width:60px;height:60px}.relation-section /deep/ .cell{white-space:pre-wrap;word-break:break-word}.photos{display:flex;flex-wrap:wrap;gap:12px;margin:20px 0}.photos .el-image{width:130px;height:130px}.danger-text{color:#F56C6C}.detail-scroll /deep/ .el-descriptions-item__content{white-space:pre-wrap;word-break:break-all}@media(max-width:1000px){.stats{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
