const api = require('../../utils/api'); const ui = require('../../utils/ui')
Page({ data: { user: null, nickname: '', avatar: '', editing: false, loading: false, saving: false, error: '' }, onShow() { if (!this.data.editing) this.load() }, onPullDownRefresh() { this.load().finally(() => wx.stopPullDownRefresh()) },
  async load() { await getApp().ready; this.setData({ user: getApp().globalData.user, error: '' }); if (!this.data.user) return; this.setData({ loading: true }); try { const user = await api.get('pet/profile'); getApp().globalData.user = user; this.setData({ user, nickname: user.nickname, avatar: user.avatar }) } catch (e) { this.setData({ error: e.message }) } finally { this.setData({ loading: false }) } },
  login() { wx.navigateTo({ url: '/pages/login/index' }) }, stopScroll() { return false }, edit() { if (this.data.saving || !this.data.user) return; this.setData({ editing: !this.data.editing, nickname: this.data.user.nickname, avatar: this.data.user.avatar }) }, input(e) { this.setData({ nickname: e.detail.value }) },
  async avatar(e) { try { this.setData({ saving: true }); this.setData({ avatar: await api.upload(e.detail.avatarUrl) }) } catch (err) { ui.error(err) } finally { this.setData({ saving: false }) } },
  async save() { if (this.data.saving) return; const nickname = this.data.nickname.trim(); if (!nickname) return ui.error(new Error('请输入昵称')); this.setData({ nickname }); this.setData({ saving: true }); try { const user = await api.post('pet/saveProfile', { nickname: this.data.nickname, avatar: this.data.avatar }); getApp().globalData.user = user; this.setData({ user, editing: false }); wx.showToast({ title: '资料已保存' }) } catch (e) { ui.error(e) } finally { this.setData({ saving: false }) } },
  async go(e) { const path = e.currentTarget.dataset.path; if (!path.startsWith('info') && !await ui.auth()) return; if (path === 'pets') wx.switchTab({ url: '/pages/pets/index' }); else wx.navigateTo({ url: '/pages/' + path }) },
  async logout() { if (!await ui.confirm('确认退出当前账号吗？')) return; try { await api.post('pet/logout'); getApp().clearSession(); this.setData({ user: null, editing: false }) } catch (e) { ui.error(e) } }
})
