#!/bin/bash

# 清理调试代码脚本
# 用于清理项目中的调试代码和 TODO 注释

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# 检查是否在项目根目录
if [ ! -f "composer.json" ]; then
    error "请在项目根目录执行此脚本"
    exit 1
fi

info "开始清理调试代码..."

# 统计清理前的代码
DEBUG_COUNT_BEFORE=$(grep -r "print_r\|var_dump\|dd(\|dump(" app --include="*.php" 2>/dev/null | wc -l | tr -d ' ')
TODO_COUNT_BEFORE=$(grep -r "TODO:" app --include="*.php" 2>/dev/null | wc -l | tr -d ' ')

info "清理前统计："
echo "  调试代码: $DEBUG_COUNT_BEFORE 处"
echo "  TODO注释: $TODO_COUNT_BEFORE 处"

# 确认操作
read -p "确定要继续清理吗？(y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    info "操作已取消"
    exit 0
fi

# 清理调试代码（注释掉，不删除，便于审查）
info "清理调试代码..."
find app -name "*.php" -type f -exec sed -i.bak '/print_r\|var_dump\|dd(\|dump(/s/^/\/\/ DEBUG: /' {} \; 2>/dev/null || true

# 清理 TODO 注释（仅清理无意义的 TODO）
info "清理无意义的 TODO 注释..."
find app -name "*.php" -type f -exec sed -i.bak 's/\/\/ TODO: Change the autogenerated stub//g' {} \; 2>/dev/null || true

# 删除备份文件
find app -name "*.bak" -type f -delete 2>/dev/null || true

# 统计清理后的代码
DEBUG_COUNT_AFTER=$(grep -r "print_r\|var_dump\|dd(\|dump(" app --include="*.php" 2>/dev/null | wc -l | tr -d ' ')
TODO_COUNT_AFTER=$(grep -r "TODO:" app --include="*.php" 2>/dev/null | wc -l | tr -d ' ')

info "清理完成！"
echo ""
info "清理后统计："
echo "  调试代码: $DEBUG_COUNT_AFTER 处（已注释）"
echo "  TODO注释: $TODO_COUNT_AFTER 处"
echo ""
warn "注意："
echo "  1. 调试代码已注释，请手动审查后删除"
echo "  2. 部分 TODO 已清理，请检查是否有遗漏"
echo "  3. 建议使用 Git 查看变更：git diff"

